import { SettingSchemaDesc } from "@logseq/libs/dist/LSPlugin.user";

export const settings: SettingSchemaDesc[] = [
  {
    key: "startOfWeek",
    type: "enum",
    default: "Sunday",
    title: "Start of Week",
    description: "Select the day that starting the week.",
    enumChoices: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday"
    ],
  },
  {
    key: "dayFormat",
    type: "string",
    default: "MMM do, yyyy",
    title: "Day Format",
    description: "Format for the day/journal page name.",
  },
  {
    key: "weekFormat",
    type: "string",
    default: "Www yyyy",
    title: "Week Page Format",
    description: "Format for the week page name.",
  },
  {
    key: "monthFormat",
    type: "string",
    default: "MMMM yyyy",
    title: "Month Page Format",
    description: "Format for the month page name.",
  },
  {
    key: "quarterFormat",
    type: "string",
    default: "QQ yyyy",
    title: "Quarter Page Format",
    description: "Format for the quarter page name.",
  },
  {
    key: "yearFormat",
    type: "string",
    default: "yyyy",
    title: "Year Page Format",
    description: "Format for the year page name.",
  },
  {
    key: "dayTags",
    type: "string",
    default: "",
    title: "Day Page Tag",
    description: "Optional tag to append to the daily page name (e.g. '#daily #anything').",
  },
  {
    key: "weekTags",
    type: "string",
    default: "",
    title: "Week Page Tag",
    description: "Optional tag to append to the weekly page name (e.g. '#week #anything').",
  },
  {
    key: "monthTags",
    type: "string",
    default: "",
    title: "Month Page Tag",
    description: "Optional tag to append to the monthly page name (e.g. '#month #anything').",
  },
  {
    key: "quarterTags",
    type: "string",
    default: "",
    title: "Quarter Page Tag",
    description: "Optional tag to append to the quarterly page name (e.g. '#quarter #anything').",
  },
  {
    key: "yearTags",
    type: "string",
    default: "",
    title: "Year Page Tag",
    description: "Optional tag to append to the yearly page name (e.g. '#year #anything').",
  },
  {
    key: "autoCreatePage",
    type: "boolean",
    default: false,
    title: "Auto Create Empty Page",
    description: "If enabled, clicking a date or custom page link that does not exist will automatically create and navigate to it without asking for confirmation.",
  },
  {
    key: "showExistIndicator",
    type: "boolean",
    default: true,
    title: "Show Exist Indicator",
    description: "If enabled, showing an indicator (dots for days, underlines for other links) for pages that already exist in your graph.",
  },
];